[[redirects]]
  from = "/*"
<<<<<<< HEAD
  to = "/registro.html"
=======
<<<<<<< HEAD
  to = "/templates/registro.html"
=======
  to = "/registro.html"
>>>>>>> d93b24f (beta)
>>>>>>> dc557fa (Beta)
  status = 200
